export {
  buildInitPlan,
  buildSetupPlan,
  discoverSkillTargets,
  executeInit,
  executeSkillInstall,
  formatMcpJsonSnippet,
  formatVscodeMcpJson,
  getPackageRoot,
  parseInitArgs,
  parseSetupArgs,
  printInitHelp,
  printInitSuccess,
  printSetupHelp,
  runInit,
  runSetup,
  VALID_IDES,
  type IdeTarget,
  type InitOptions,
  type InitPlan,
  type SetupOptions,
  type SetupPlan,
  type SkillInstallTarget,
} from './setup.js';
